# Generated by Django 5.0.2 on 2024-03-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connecthub', '0002_post_caption_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(default='images/default2.png', upload_to='profile_pic1'),
        ),
    ]
