# Generated by Django 5.0.2 on 2024-03-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connecthub', '0005_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(default='django2\\project3\\connecthub\\static\\images', upload_to='profile_pic1'),
        ),
    ]
