# Generated by Django 5.0.2 on 2024-03-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connecthub', '0012_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='hey there im using connecthub', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic1'),
        ),
    ]
