# Generated by Django 5.0.2 on 2024-03-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connecthub', '0013_alter_profile_bio_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(blank=True, default='django2/project3/static/images/default2.png', null=True, upload_to='profile_pic1'),
        ),
    ]
