# Generated by Django 5.0.2 on 2024-03-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connecthub', '0014_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(blank=True, default='src="django2/project3/static/images/default2.png"', null=True, upload_to='profile_pic1'),
        ),
    ]
